# Generated by Django 3.0.5 on 2020-11-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
