# Generated by Django 3.0.5 on 2020-11-09 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_item_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='views',
        ),
    ]
